apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: sample-jboss
  name: sample-jboss-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30903
  selector:
    name: sample-jboss
  type: NodePort
